spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/courseregistration
    username: root
    password: Venki@123
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    